name: model-training
on:
  pull_request:
    branches: main
permissions: write-all
jobs:
  train_and_publish_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python train.py

      - name: Setup CML
        uses: iterative/setup-cml@v1
      
      - name: Create and publish CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Generating report"
          cat metrics.txt >> report.md
          echo "![](./confusion_matrix.png)" >> report.md

          echo "Creating comment"
          cml comment create report.md