name: model-training
on:
  pull_request:
    branches: main
permissions: write-all
jobs:
  train_and_publish_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Run DVC pipeline
        run: dvc repro

      - name: Setup CML
        uses: iterative/setup-cml@v1
      
      - name: Create and publish metrics diff report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          git fetch --prune
          echo "Generating report"
          # echo "## Metrics" >> report.md
          # dvc metrics diff --show-md main >> report.md
          dvc metrics show --md >> report.md
          
          # echo "## Plots" >> report.md
          # echo "### Confusion matrix" >> report.md
          # echo "![](./confusion_matrix.png)" >> report.md
          # echo "### Class confusions" >> report.md
          # dvc plots diff --target predictions.csv --template confusion -x true_label -y predicted_label --show-vega main > vega.json
          # vl2png vega.json -s 1.5 > confusion_plot.png
          # echo "![](./confusion_plot.png)" >> report.md

          echo "Creating comment"
          cml comment create report.md
